export const STAKED_BRB_CONTRACT_ADDRESS = "0xe97f3f00e8b95c15153b2b25dafc61cb51f29b6b"
export const JACKPOT_CONTRACT_ADDRESS = "0x2e82fc04fdf70329102cd41d4881e02a1185c56b"
export const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"
// Constants for bet types (same as in roulette.ts)
export const BET_STRAIGHT = 1
export const BET_SPLIT = 2
export const BET_STREET = 3
export const BET_CORNER = 4
export const BET_LINE = 5
export const BET_COLUMN = 6
export const BET_DOZEN = 7
export const BET_RED = 8
export const BET_BLACK = 9
export const BET_ODD = 10
export const BET_EVEN = 11
export const BET_LOW = 12
export const BET_HIGH = 13
export const BET_TRIO_012 = 14
export const BET_TRIO_023 = 15

// Constants for round status
export const ROUND_STATUS_BETTING = "BETTING"
export const ROUND_STATUS_NO_MORE_BETS = "NO_MORE_BETS"
export const ROUND_STATUS_VRF = "VRF"
export const ROUND_STATUS_COMPUTING_PAYOUT = "COMPUTING_PAYOUT"
export const ROUND_STATUS_PAYOUT = "PAYOUT"
export const ROUND_STATUS_CLEAN = "CLEAN"

// Constants for bet types
export const BET_TYPE_STRAIGHT = "STRAIGHT"
export const BET_TYPE_SPLIT = "SPLIT"
export const BET_TYPE_STREET = "STREET"
export const BET_TYPE_CORNER = "CORNER"
export const BET_TYPE_LINE = "LINE"
export const BET_TYPE_COLUMN = "COLUMN"
export const BET_TYPE_DOZEN = "DOZEN"
export const BET_TYPE_RED = "RED"
export const BET_TYPE_BLACK = "BLACK"
export const BET_TYPE_ODD = "ODD"
export const BET_TYPE_EVEN = "EVEN"
export const BET_TYPE_LOW = "LOW"
export const BET_TYPE_HIGH = "HIGH"
export const BET_TYPE_TRIO_012 = "TRIO_012"
export const BET_TYPE_TRIO_023 = "TRIO_023"
